<?php

use Illuminate\Database\Seeder;

class MatHangTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('MatHangTable')->insert([
        		'id'		=>'1',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>1,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm a',
	            'BiDanh'=>'ah1',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Hàn Quốc',
	            'GiaTriKLT'=>'32',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>321000,
	            'GiaBan'=>450000,
	            'GiaGiam'=>15000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>25,
	            'Tinhtrang'=>1,
    	]);
         DB::table('MatHangTable')->insert([
        		'id'		=>'2',
	            'id_Xuatxu' =>  '2', 
	            'id_MaLoai'=>1,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm d',
	            'BiDanh'=>'ah2',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Hàn Quốc',
	            'GiaTriKLT'=>'15',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>210000,
	            'GiaBan'=>480000,
	            'GiaGiam'=>35000,
	            'MaSPKM'=>'KM2',
	            'SLKM'=>25,
	            'Tinhtrang'=>1,
    	]);
         DB::table('MatHangTable')->insert([
        		'id'		=>'3',
	            'id_Xuatxu' =>  '1', 
	            'id_MaLoai'=>1,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm c',
	            'BiDanh'=>'ah3',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Mỹ',
	            'GiaTriKLT'=>'22',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>421000,
	            'GiaBan'=>580000,
	            'GiaGiam'=>15000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>25,
	            'Tinhtrang'=>1,
    	]);
         DB::table('MatHangTable')->insert([
        		'id'		=>'4',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>2,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm d',
	            'BiDanh'=>'ah4',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Pháp',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>221000,
	            'GiaBan'=>350000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>25,
	            'Tinhtrang'=>1,
    	]);
          DB::table('MatHangTable')->insert([
        		'id'		=>'5',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>2,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm e',
	            'BiDanh'=>'ah5',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Pháp',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>221000,
	            'GiaBan'=>650000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
           DB::table('MatHangTable')->insert([
        		'id'		=>'6',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>2,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm f',
	            'BiDanh'=>'ah6',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Pháp',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>221000,
	            'GiaBan'=>650000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
            DB::table('MatHangTable')->insert([
        		'id'		=>'7',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>3,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm g',
	            'BiDanh'=>'ah7',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Pháp',
	            'GiaTriKLT'=>'13',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>375000,
	            'GiaBan'=>550000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
             DB::table('MatHangTable')->insert([
        		'id'		=>'8',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>3,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm h',
	            'BiDanh'=>'ah8',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Anh',
	            'GiaTriKLT'=>'15',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>250000,
	            'GiaBan'=>650000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
              DB::table('MatHangTable')->insert([
        		'id'		=>'9',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>3,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm i',
	            'BiDanh'=>'ah9',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Pháp',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>421000,
	            'GiaBan'=>550000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
               DB::table('MatHangTable')->insert([
        		'id'		=>'10',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>3,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm k',
	            'BiDanh'=>'ah10',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Trung Quốc',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>420000,
	            'GiaBan'=>550000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
               DB::table('MatHangTable')->insert([
        		'id'		=>'11',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>3,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm l',
	            'BiDanh'=>'ah11',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Trung Quốc',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>250000,
	            'GiaBan'=>350000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
               DB::table('MatHangTable')->insert([
        		'id'		=>'12',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>2,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm m',
	            'BiDanh'=>'ah12',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Trung Quốc',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>520000,
	            'GiaBan'=>650000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
               DB::table('MatHangTable')->insert([
        		'id'		=>'13',
	            'id_Xuatxu' =>  '3', 
	            'id_MaLoai'=>1,
	            'id_LKLT'=>"1",
	            'id_LDVT'=>2,
	            'id_NhaCC'=>,
	            'TenMH'=>'Sản Phẩm n',
	            'BiDanh'=>'ah13',
	            'TenThuonghieu'=>'Olay',
	            'TenXuatXu'=>'Mỹ',
	            'GiaTriKLT'=>'18',
	            'GiaTriDVT'=>'1',
	            'MoTaSP'=>'không mô tả',
	            'Hinh'=>'',
	            'GiaNhap'=>420000,
	            'GiaBan'=>550000,
	            'GiaGiam'=>25000,
	            'MaSPKM'=>'KM1',
	            'SLKM'=>20,
	            'Tinhtrang'=>1,
    	]);
    }
}
